project:
  type: website

website:
  title: "Doc de Ener-Habitat"
  image: "images/enerhabitat.jpg"
  favicon: "images/logo_edited.png"
  repo-url: https://github.com/AltamarMx
  page-navigation: true
  search: 
    show-item-context: true
    type: overlay
  page-footer: 
    left: |
      Derechos de autor . 2024 Documentacion de Ener-Habitat. Todos los derechos reservados
  navbar:
    background: light
    logo: images/enerhabitat.jpg
    logo-alt: "EnerHabitat logo."
    title: false
    collapse-below: xl
    left:
      - text: "Inicio"
        href: index.qmd
    tools:
      - icon: github
        href:  https://github.com/AltamarMx
        text: Learn Python
    
  sidebar: 
  - id: get-started
    text: "Empezar"
    style: floating
    collapse-level: 2
    align: left
    contents:
        - docs/index.qmd
        - text: "Desarrollo de interfaz"
          href: docs/interfaz.qmd
        - text: "Diccionarios"
          href: docs/diccionaries.qmd
        - text: "Archivos creados"
          href: docs/archivos.qmd
        - text: "Funciones"
          href: docs/funciones.qmd
        - text: "Funciones para renderizar"
          href: docs/server.qmd
        - text: "Base de datos"
          href: docs/bd.qmd

format:
  html:
    light: [cosmo, theme.scss]
    toc: true
    code-copy: true

freeze: true




