project:
  type: website

website:
  title: "EnerHabitat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: CSS/styles.css
    toc: true



